/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#d1dce0",
        "on-primary-fixed-variant": "#713700",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#161d1f",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "surface-container-highest": "#d9e4e9",
        "on-primary": "#ffffff",
        "tertiary": "#625e56",
        "surface-variant": "#d9e4e9",
        "primary-fixed-dim": "#ffb783",
        "outline-variant": "#dcc1b1",
        "surface-bright": "#f1fbff",
        "primary": "#944a00",
        "outline": "#897365",
        "background": "#f1fbff",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#dfeaef",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#e7f3f7",
        "primary-fixed": "#ffdcc5",
        "inverse-surface": "#283236",
        "on-secondary-container": "#5d6466",
        "surface-container-low": "#eaf5fa",
        "tertiary-fixed": "#e9e1d8",
        "on-secondary-fixed-variant": "#41484a",
        "on-tertiary-fixed": "#1e1b15",
        "tertiary-container": "#9e988f",
        "on-primary-container": "#502600",
        "on-primary-fixed": "#301400",
        "on-tertiary-fixed-variant": "#4a463f",
        "on-tertiary-container": "#34312a",
        "tertiary-fixed-dim": "#cdc5bc",
        "on-background": "#131d21",
        "on-surface": "#131d21",
        "on-surface-variant": "#564337",
        "surface-container": "#e4f0f4",
        "secondary": "#586062",
        "secondary-fixed": "#dde4e6",
        "surface": "#f1fbff",
        "secondary-fixed-dim": "#c1c8ca",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#944a00",
        "secondary-container": "#dae1e3",
        "primary-container": "#e67e22",
        "inverse-primary": "#ffb783",
        "on-error": "#ffffff"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        sm: "12px",
        "container-max": "1200px",
        base: "8px",
        xs: "4px",
        md: "24px",
        lg: "48px",
        xl: "80px",
        "margin-desktop": "40px",
        gutter: "24px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Work Sans", "sans-serif"],
        "body-lg": ["Work Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "label-bold": ["Work Sans", "sans-serif"],
        "body-sm": ["Work Sans", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "display-lg-mobile": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "label-bold": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}]
      }
    }
  },
  plugins: [require('@tailwindcss/forms')],
};
