import { register,login,forgotPassword,resetPassword,getAllUsersController,getProfile,verifyEmail } from "../controller/authController";
import { authMiddleware } from "../middleware/authMiddleWare";
import express from express;
const authRouter = express.Router();
authRouter.post('/register',authMiddleware,register);
authRouter.post('/login',authMiddleware,login);
authRouter.get('/forgot-password',authMiddleware,forgotPassword);
authRouter.post('/reset-password',authMiddleware,resetPassword);
authRouter.get('/profile',authMiddleware,getProfile);
authRouter.post('/verify-email',authMiddleware,verifyEmail);
authRouter.get('/users',authMiddleware,getAllUsersController);
export default authRouter;